spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saasdb
    username: saasuser
    password: saaspass
  jpa:
    show-sql: true
  h2:
    console:
      enabled: false

logging:
  level:
    com.saas: DEBUG
